### PR TITLE
Mr bago remove dti tensor

### PR DESCRIPTION
**Pull request by arokem**
While we're at it. Here's a little bit of a cleanup of some boiler-plate and implementation of some new tensor statistics.

### CODE REVIEW

**Comment by MrBago** [comment]
This looks good to me @arokem , but I don't see any reason it couldn't be a standalone pull request. It's starting to worry me that we have so many `@auto_attr`s on the tensor fit. `auto_attrs` have a dark side because they are essentially intentional memory leaks. Long term I'd like to think about strategies to address this, my preference has always been `fit.fa()` over `fit.fa`, but I think that boat has sailed.

**Comment by arokem** [comment]
The reason I didn't want this as a stand-alone pull request is that I wanted this to not conflict with the changes you were making. But you know what, let's focus on merging your stuff in and do this later. At least the first commit here can be included in your PR, no? Then, I can make another PR against dipy/master for the Westin stats and we can discuss the autoattrs in more details.

**Comment by arokem** [comment]
And of course - the Westin stats still need tests anyway

**Comment by arokem** [comment]
To wit: 

https://travis-ci.org/MrBago/dipy/builds/6227538

Sorry about that!

**Pull request closed without merging**
